name: Format Code

on:
  push:
    paths:
      - '*.js'
      - '*.json'
      - '*.py'
      - '*.yml'
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  formatting:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      
      - name: Install Black
        run: pip install black
      
      - name: Run Black
        run: black .

      - name: Prettier Action
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,json,yml}
          commit_message: "Apply code formatting"
