name: Code Formatting and Style

on:
  push:
    paths:
      - '*.js'
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  formatting:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Prettier Action
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write unobfuscated/**/*.js src/**/*.js
          commit_message: "style: apply code formatting standards"
