name: Format Code

on:
  push:
    paths:
      - '*.js'
      - '*.json'
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  formatting:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Prettier Action
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write unobfuscated/**/*.js src/**/*.js **/*.json
          commit_message: "Apply code formatting"
