name: Format Code

on:
  push:
    branches:
      - Diana
  pull_request:
    branches:
      - Diana
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout code
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Prettier
        run: npm install --global prettier

      - name: Prettier Action
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,json,html,css,yml,md} --ignore-unknown
          commit_message: "Apply code formatting"
        continue-on-error: true
